class Currency {
  final String code;
  final String name;
  final String symbol;

  Currency({
    required this.code,
    required this.name,
    required this.symbol,
  });

  @override
  String toString() => '$name ($symbol)';
}

class AppCurrencies {
  static final List<Currency> all = [
    Currency(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ'),
    Currency(code: 'AFN', name: 'Afghan Afghani', symbol: '؋'),
    Currency(code: 'ALL', name: 'Albanian Lek', symbol: 'L'),
    Currency(code: 'AMD', name: 'Armenian Dram', symbol: '֏'),
    Currency(code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ'),
    Currency(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz'),
    Currency(code: 'ARS', name: 'Argentine Peso', symbol: '\$'),
    Currency(code: 'AUD', name: 'Australian Dollar', symbol: '\$'),
    Currency(code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ'),
    Currency(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼'),
    Currency(code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM'),
    Currency(code: 'BBD', name: 'Barbadian Dollar', symbol: '\$'),
    Currency(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳'),
    Currency(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв'),
    Currency(code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب'),
    Currency(code: 'BIF', name: 'Burundian Franc', symbol: 'FBu'),
    Currency(code: 'BMD', name: 'Bermudan Dollar', symbol: '\$'),
    Currency(code: 'BND', name: 'Brunei Dollar', symbol: '\$'),
    Currency(code: 'BOB', name: 'Bolivian Boliviano', symbol: '\$b'),
    Currency(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$'),
    Currency(code: 'BSD', name: 'Bahamian Dollar', symbol: '\$'),
    Currency(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.'),
    Currency(code: 'BWP', name: 'Botswanan Pula', symbol: 'P'),
    Currency(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br'),
    Currency(code: 'BZD', name: 'Belize Dollar', symbol: 'BZ\$'),
    Currency(code: 'CAD', name: 'Canadian Dollar', symbol: '\$'),
    Currency(code: 'CDF', name: 'Congolese Franc', symbol: 'FC'),
    Currency(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF'),
    Currency(code: 'CLP', name: 'Chilean Peso', symbol: '\$'),
    Currency(code: 'CNY', name: 'Chinese Yuan', symbol: '¥'),
    Currency(code: 'COP', name: 'Colombian Peso', symbol: '\$'),
    Currency(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡'),
    Currency(code: 'CUP', name: 'Cuban Peso', symbol: '\$'),
    Currency(code: 'CVE', name: 'Cape Verdean Escudo', symbol: '\$'),
    Currency(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč'),
    Currency(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj'),
    Currency(code: 'DKK', name: 'Danish Krone', symbol: 'kr'),
    Currency(code: 'DOP', name: 'Dominican Peso', symbol: 'RD\$'),
    Currency(code: 'DZD', name: 'Algerian Dinar', symbol: 'دج'),
    Currency(code: 'EGP', name: 'Egyptian Pound', symbol: '£'),
    Currency(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk'),
    Currency(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br'),
    Currency(code: 'EUR', name: 'Euro', symbol: '€'),
    Currency(code: 'FJD', name: 'Fijian Dollar', symbol: '\$'),
    Currency(code: 'FKP', name: 'Falkland Islands Pound', symbol: '£'),
    Currency(code: 'GBP', name: 'British Pound', symbol: '£'),
    Currency(code: 'GEL', name: 'Georgian Lari', symbol: '₾'),
    Currency(code: 'GGP', name: 'Guernsey Pound', symbol: '£'),
    Currency(code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵'),
    Currency(code: 'GIP', name: 'Gibraltar Pound', symbol: '£'),
    Currency(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D'),
    Currency(code: 'GNF', name: 'Guinean Franc', symbol: 'FG'),
    Currency(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q'),
    Currency(code: 'GYD', name: 'Guyanaese Dollar', symbol: '\$'),
    Currency(code: 'HKD', name: 'Hong Kong Dollar', symbol: '\$'),
    Currency(code: 'HNL', name: 'Honduran Lempira', symbol: 'L'),
    Currency(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn'),
    Currency(code: 'HTG', name: 'Haitian Gourde', symbol: 'G'),
    Currency(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft'),
    Currency(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp'),
    Currency(code: 'ILS', name: 'Israeli New Shekel', symbol: '₪'),
    Currency(code: 'IMP', name: 'Isle of Man Pound', symbol: '£'),
    Currency(code: 'INR', name: 'Indian Rupee', symbol: '₹'),
    Currency(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د'),
    Currency(code: 'IRR', name: 'Iranian Rial', symbol: '﷼'),
    Currency(code: 'ISK', name: 'Icelandic Króna', symbol: 'kr'),
    Currency(code: 'JEP', name: 'Jersey Pound', symbol: '£'),
    Currency(code: 'JMD', name: 'Jamaican Dollar', symbol: 'J\$'),
    Currency(code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD'),
    Currency(code: 'JPY', name: 'Japanese Yen', symbol: '¥'),
    Currency(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh'),
    Currency(code: 'KGS', name: 'Kyrgystani Som', symbol: 'лв'),
    Currency(code: 'KHR', name: 'Cambodian Riel', symbol: '៛'),
    Currency(code: 'KMF', name: 'Comorian Franc', symbol: 'CF'),
    Currency(code: 'KPW', name: 'North Korean Won', symbol: '₩'),
    Currency(code: 'KRW', name: 'South Korean Won', symbol: '₩'),
    Currency(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD'),
    Currency(code: 'KYD', name: 'Cayman Islands Dollar', symbol: '\$'),
    Currency(code: 'KZT', name: 'Kazakhstani Tenge', symbol: 'лв'),
    Currency(code: 'LAK', name: 'Laotian Kip', symbol: '₭'),
    Currency(code: 'LBP', name: 'Lebanese Pound', symbol: '£'),
    Currency(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs'),
    Currency(code: 'LRD', name: 'Liberian Dollar', symbol: '\$'),
    Currency(code: 'LSL', name: 'Lesotho Loti', symbol: 'L'),
    Currency(code: 'LYD', name: 'Libyan Dinar', symbol: 'LD'),
    Currency(code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD'),
    Currency(code: 'MDL', name: 'Moldovan Leu', symbol: 'L'),
    Currency(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar'),
    Currency(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден'),
    Currency(code: 'MMK', name: 'Myanmar Kyat', symbol: 'K'),
    Currency(code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮'),
    Currency(code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP\$'),
    Currency(code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM'),
    Currency(code: 'MUR', name: 'Mauritian Rupee', symbol: 'Rs'),
    Currency(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf'),
    Currency(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK'),
    Currency(code: 'MXN', name: 'Mexican Peso', symbol: '\$'),
    Currency(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM'),
    Currency(code: 'MZN', name: 'Mozambican Metical', symbol: 'MT'),
    Currency(code: 'NAD', name: 'Namibian Dollar', symbol: '\$'),
    Currency(code: 'NGN', name: 'Nigerian Naira', symbol: '₦'),
    Currency(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C\$'),
    Currency(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr'),
    Currency(code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs'),
    Currency(code: 'NZD', name: 'New Zealand Dollar', symbol: '\$'),
    Currency(code: 'OMR', name: 'Omani Rial', symbol: '﷼'),
    Currency(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.'),
    Currency(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.'),
    Currency(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K'),
    Currency(code: 'PHP', name: 'Philippine Peso', symbol: '₱'),
    Currency(code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs'),
    Currency(code: 'PLN', name: 'Polish Zloty', symbol: 'zł'),
    Currency(code: 'PYG', name: 'Paraguayan Guarani', symbol: 'Gs'),
    Currency(code: 'QAR', name: 'Qatari Riyal', symbol: '﷼'),
    Currency(code: 'RON', name: 'Romanian Leu', symbol: 'lei'),
    Currency(code: 'RSD', name: 'Serbian Dinar', symbol: 'Дин.'),
    Currency(code: 'RUB', name: 'Russian Ruble', symbol: '₽'),
    Currency(code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw'),
    Currency(code: 'SAR', name: 'Saudi Riyal', symbol: '﷼'),
    Currency(code: 'SBD', name: 'Solomon Islands Dollar', symbol: '\$'),
    Currency(code: 'SCR', name: 'Seychellois Rupee', symbol: 'Rs'),
    Currency(code: 'SDG', name: 'Sudanese Pound', symbol: '£'),
    Currency(code: 'SEK', name: 'Swedish Krona', symbol: 'kr'),
    Currency(code: 'SGD', name: 'Singapore Dollar', symbol: '\$'),
    Currency(code: 'SHP', name: 'Saint Helena Pound', symbol: '£'),
    Currency(code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le'),
    Currency(code: 'SOS', name: 'Somali Shilling', symbol: 'S'),
    Currency(code: 'SRD', name: 'Surinamese Dollar', symbol: '\$'),
    Currency(code: 'SSP', name: 'South Sudanese Pound', symbol: '£'),
    Currency(code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db'),
    Currency(code: 'SVC', name: 'Salvadoran Colón', symbol: '\$'),
    Currency(code: 'SYP', name: 'Syrian Pound', symbol: '£'),
    Currency(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L'),
    Currency(code: 'THB', name: 'Thai Baht', symbol: '฿'),
    Currency(code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM'),
    Currency(code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T'),
    Currency(code: 'TND', name: 'Tunisian Dinar', symbol: 'DT'),
    Currency(code: 'TOP', name: 'Tongan Pa\'anga', symbol: 'T\$'),
    Currency(code: 'TRY', name: 'Turkish Lira', symbol: '₺'),
    Currency(code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT\$'),
    Currency(code: 'TVD', name: 'Tuvaluan Dollar', symbol: '\$'),
    Currency(code: 'TWD', name: 'Taiwan New Dollar', symbol: 'NT\$'),
    Currency(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh'),
    Currency(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴'),
    Currency(code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh'),
    Currency(code: 'USD', name: 'US Dollar', symbol: '\$'),
    Currency(code: 'UYU', name: 'Uruguayan Peso', symbol: '\$'),
    Currency(code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв'),
    Currency(code: 'VES', name: 'Venezuelan Bolívar', symbol: '\$'),
    Currency(code: 'VND', name: 'Vietnamese Dong', symbol: '₫'),
    Currency(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT'),
    Currency(code: 'WST', name: 'Samoan Tala', symbol: 'WS\$'),
    Currency(code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA'),
    Currency(code: 'XCD', name: 'East Caribbean Dollar', symbol: '\$'),
    Currency(code: 'XDR', name: 'Special Drawing Rights', symbol: 'SDR'),
    Currency(code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA'),
    Currency(code: 'XPF', name: 'CFP Franc', symbol: '₣'),
    Currency(code: 'YER', name: 'Yemeni Rial', symbol: '﷼'),
    Currency(code: 'ZAR', name: 'South African Rand', symbol: 'R'),
    Currency(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK'),
    Currency(code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z\$'),
  ];

  static Currency getDefault() => all.firstWhere((c) => c.code == 'USD');

  static Currency? findByCode(String code) {
    try {
      return all.firstWhere((c) => c.code == code);
    } catch (e) {
      return null;
    }
  }
}